site_name: Trabalho 3 - Lakehouse Databricks (Medalhão)
site_url: https://castroderaul23.github.io/lakehouse_medalhao_brasileiro/
nav:
  - Início: index.md
  - Arquitetura Medalhão: arquitetura.md
  - Pipeline (Notebooks): pipeline.md
  - Star Schema (Gold): star_schema.md
  - Job (Execução): job.md
theme:
  name: mkdocs
